import { Injectable } from '@angular/core'

@Injectable({
  providedIn: 'root'
})
export class SetUpIds {

  public static get catLevel (): number {
    return 1
  }

  public static get dateFormat (): number {
    return 39
  }

  public static get currency (): number {
    return 37
  }

  public static get noOfDecimalPoint (): number {
    return 43
  }

  public static get unitType (): number {
    return 56
  }

  public static get backDateEntry (): number {
    return 58
  }

  public static get godamWiseStockManagement (): number {
    return 5
  }

  public static get gstCalculationOnFreightOrOtherChange (): number {
    return 57
  }

  public static get allowForAdvancePayment (): number {
    return 59
  }

  public static get purchaseBillNoManually (): number {
    return 60
  }

  public static get multiple (): number {
    return 4
  }

  public static get singleVal (): number {
    return 3
  }

  public static get singleId (): number {
    return 5
  }

  public static get getBoolean (): number {
    return 1
  }

  public static get getStrOrNum (): number {
    return 2
  }

  public static get baseTypeNum (): number {
    return 1
  }

  public static get baseTypeStr (): number {
    return 2
  }

  public static get taxCalInclusive (): number {
    return 66
  }
  public static get itemInStockForSale (): number {
    return 3
  }
  public static get PrintWithSave (): number {
    return 57
  }
  public static get DisabledTaxSlab (): number {
    return 9
  }
  public static get PaidUnpaidOnBIllShow (): number {
    return 65
  }
  public static get DiscountFor100 (): number {
    return 2
  }
  public static get paymentAutoVoucher (): number {
    return 68
  }

  public static get receiptAutoVoucher (): number {
    return 69
  }

  public static get billSettlementType (): number {
    return 70
  }
  public static get backDateEntryForSale (): number {
    return 41
  }
  public static get applyCustomRateOnItemForSale (): number {
    return 12
  }
  public static get isManualBillNoEntryForsale (): number {
    return 22
  }
  public static get isManualBillNoEntryForsaleDirectReturn (): number {
    return 26
  }

  public static get autoGeneratedBarcode (): number {
    return 32
  }

  public static get autoGneratedItemCode (): number {
    return 64
  }
  
  public static get edgerAddressRequiredorNot (): number {
    return 54
  }
  
  public static get edgerEmailorMobileRequiredorNot (): number {
    return 55
  }
  public static get printFormate () : number {
    return 77
  }
  public static get MultipleBillDiscount (): number {
    return 20
  }
  public static get MultipleBillDiscountPurchase (): number {
    return 30
  }
  public static get BillDiscountOnPrint (): number {
    return 27
  }
  public static get multipleBillSettlement (): number {
    return 78
  }
  public static get PaymentDatilsOnPrint_Sale_ServiceSale (): number {
    return 63
  }
  public static get categoryShowOnPrint (): number {
    return 25
  }
  public static get BarCodeEnable ():number {
    return 10
  }
  public static get attributesForPurchase ():number {
    return 29
  }

  public static get defaultMesurementUnit ():number {
    return 74
  }
  public static get buyerOrderAttributes ():number {
    return 76
  }
  public static get manualEntryBuyerOrder ():number {
    return 73
  }
  public static get applyRevugainAPI ():number {
    return 79
  }
  public static get RevugainAPIKey ():number {
    return 80
  }
  public static get AttributeForRequirement ():number {
    return 19
  }
  public static get PackagingCodeManual ():number {
    return 87
  }
  public static get isManualBillNoEntryForChallanSale (): number {
    return 61
  }
  public static get SignatorySetup (): number {
    return 89
  }
  public static get HideCategoryOnSale (): number {
    return 92
  }
  public static get HideCategoryOnPurchase (): number {
    return 93
  }
  public static get HideItem_Discount (): number {
    return 94
  }
  public static get HideTax_Details (): number {
    return 95
  }

}
