export class DateFormats {
  public static get data (): Array<any> {
    return  [
        {
            "UId": 1,
            "CommonCode": 137,
            "Val": "DD-MM-YYYY",
            "ShortName": "d-m-Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 542,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 2,
            "CommonCode": 137,
            "Val": "MM-DD-YYYY",
            "ShortName": "m-d-Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 543,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 3,
            "CommonCode": 137,
            "Val": "DD MMM YYYY",
            "ShortName": "d M Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 544,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 4,
            "CommonCode": 137,
            "Val": "MM/DD/YYYY",
            "ShortName": "m/d/Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 545,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 5,
            "CommonCode": 137,
            "Val": "DD/MM/YYYY",
            "ShortName": "d/m/Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 546,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 6,
            "CommonCode": 137,
            "Val": "MMM DD YY",
            "ShortName": "M d Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 547,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 7,
            "CommonCode": 137,
            "Val": "DD.MM.YYYY",
            "ShortName": "d.m.Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 548,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 8,
            "CommonCode": 137,
            "Val": "MM.DD.YYYY",
            "ShortName": "m.d.Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 549,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 9,
            "CommonCode": 137,
            "Val": "DD MMM YY",
            "ShortName": "d m y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 550,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 10,
            "CommonCode": 137,
            "Val": "MMM DD YYYY",
            "ShortName": "M d y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 551,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 11,
            "CommonCode": 137,
            "Val": "DD-MM-YY",
            "ShortName": "d-m-y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 554,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 12,
            "CommonCode": 137,
            "Val": "MM-DD-YY",
            "ShortName": "m-d-y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 555,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 13,
            "CommonCode": 137,
            "Val": "MM/DD/YY",
            "ShortName": "m/d/y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 556,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 14,
            "CommonCode": 137,
            "Val": "DD/MM/YY",
            "ShortName": "d/m/y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 557,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 15,
            "CommonCode": 137,
            "Val": "MMM/DD/YY",
            "ShortName": "M/d/y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 558,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 16,
            "CommonCode": 137,
            "Val": "MMM/DD/YYYY",
            "ShortName": "M/d/Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 559,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 17,
            "CommonCode": 137,
            "Val": "DD/MMM/YY",
            "ShortName": "d/M/y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 560,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 18,
            "CommonCode": 137,
            "Val": "DD/MMM/YYYY",
            "ShortName": "d/M/Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 561,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 19,
            "CommonCode": 137,
            "Val": "MMM.DD.YY",
            "ShortName": "M.d.y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 563,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 20,
            "CommonCode": 137,
            "Val": "MMM.DD.YYYY",
            "ShortName": "M.d.Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 564,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 21,
            "CommonCode": 137,
            "Val": "DD.MMM.YY",
            "ShortName": "d.M.y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 565,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 22,
            "CommonCode": 137,
            "Val": "DD.MMM.YYYY",
            "ShortName": "d.M.Y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 566,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 23,
            "CommonCode": 137,
            "Val": "DD.MM.YY",
            "ShortName": "d.m.y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 567,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        },
        {
            "UId": 24,
            "CommonCode": 137,
            "Val": "MM.DD.YY",
            "ShortName": "m.d.y",
            "CommonId1": [],
            "CommonId2": [],
            "CommonId3": [],
            "ItemCustomRate": [],
            "ItemGroupTrans": [],
            "ClientId": 0,
            "BranchId": 0,
            "OfficeId": 0,
            "Id": 568,
            "CreatedOn": null,
            "ModifiedOn": null,
            "CreatedIp": null,
            "ModifiedIp": null,
            "CreatedBy": 0,
            "ModifiedBy": 0,
            "IsActive": false,
            "TotalRows": 0
        }
    ]
  }
}